export const countryHu: Readonly<Record<string, string>> = {
  IT: 'Olaszország',
  FR: 'Franciaország',
  ES: 'Spanyolország',
  DE: 'Németország',
  NL: 'Hollandia',
  BE: 'Belgium',
  GB: 'Egyesült Királyság',
  AT: 'Ausztria',
  CH: 'Svájc',
  CZ: 'Csehország',
  PL: 'Lengyelország',
  HU: 'Magyarország',
  RO: 'Románia',
  PT: 'Portugália',
  GR: 'Görögország',
  DK: 'Dánia',
  SE: 'Svédország',
  NO: 'Norvégia',
  FI: 'Finnország',
  IE: 'Írország',
  IS: 'Izland',
  UA: 'Ukrajna',
  RU: 'Oroszország',
  TR: 'Törökország',
  BG: 'Bulgária',
  HR: 'Horvátország',
  SI: 'Szlovénia',
  SK: 'Szlovákia',
  LT: 'Litvánia',
  LV: 'Lettország',
  EE: 'Észtország',
  RS: 'Szerbia',
  BA: 'Bosznia és Hercegovina',
  MK: 'Észak-Macedónia',
  AL: 'Albánia',
  MD: 'Moldova',
  MT: 'Málta',
  LU: 'Luxemburg',
  LI: 'Liechtenstein',
  MC: 'Monaco',
  SM: 'San Marino',
  VA: 'Vatikán',
  US: 'Amerikai Egyesült Államok',
  CA: 'Kanada',
  MX: 'Mexikó',
  BR: 'Brazília',
  AR: 'Argentína',
  CL: 'Chile',
  JP: 'Japán',
  CN: 'Kína',
  KR: 'Dél-Korea',
  IN: 'India',
  EG: 'Egyiptom',
  IL: 'Izrael',
  IR: 'Irán',
  MA: 'Marokkó',
  ET: 'Etiópia',
  ZA: 'Dél-afrikai Köztársaság',
  AU: 'Ausztrália',
  NZ: 'Új-Zéland',
} as const;
