export const movementLabelsHu: Readonly<Record<string, string>> = {
  nazarene_movement: 'Nazarénus mozgalom',
  hudson_river_school: 'Hudson River School',
  luminism_usa: 'Luminizmus (USA)',
  barbizon_school: 'Barbizon-iskola',
  pre_raphaelite_brotherhood: 'Preraffaelita Testvériség',
  arts_and_crafts: 'Arts and Crafts mozgalom',
  macchiaioli: 'Macchiaioli',
  impressionism: 'Impresszionizmus',
  post_impressionism: 'Posztimpresszionizmus',
  divisionism: 'Divisionizmus',
  pointillism: 'Pointillizmus',
  les_nabis: 'Les Nabis',
  symbolist_movement: 'Szimbolista mozgalom',
  fauvism: 'Fauvizmus',
  die_brucke: 'Die Brücke',
  der_blaue_reiter: 'Der Blaue Reiter',
  expressionism: 'Expresszionizmus (mozgalom)',
  cubism: 'Kubizmus',
  futurism: 'Futurizmus',
  vorticism: 'Vorticizmus',
  rayonism: 'Rayonizmus',
  orphism: 'Orfizmus',
  metaphysical_painting: 'Metafizikus festészet (Pittura Metafisica)',
  suprematism: 'Szuprematizmus',
  constructivism: 'Konstruktivizmus',
  purism: 'Purizmus',
  de_stijl: 'De Stijl / Neoplaszticizmus',
  bauhaus: 'Bauhaus',
  dadaism: 'Dadaizmus',
  surrealism: 'Szürrealizmus',
  new_objectivity: 'Új tárgyiasság (Neue Sachlichkeit)',
  precisionism: 'Precisionizmus',
  regionalism_usa: 'Regionalizmus (USA)',
  social_realism: 'Szociális realizmus',
  mexican_muralism: 'Mexikói muralizmus',
  harlem_renaissance: 'Harlem Renaissance',
  socialist_realism: 'Szocialista realizmus',
  magic_realism: 'Magikus realizmus',
  abstract_expressionism: 'Absztrakt expresszionizmus',
  action_painting: 'Action painting',
  color_field_painting: 'Színmező-festészet',
  tachisme_art_informel: 'Tachizmus / Art Informel',
  lyrical_abstraction: 'Lírai absztrakció',
  hard_edge_painting: 'Hard-edge festészet',
  op_art: 'Op-art',
  minimalism: 'Minimalizmus',
  zero_group: 'ZERO csoport',
  nouveau_realism: 'Nouveau Réalisme',
  pop_art: 'Pop-art',
  post_painterly_abstraction: 'Poszt-painterly absztrakció',
  arte_povera: 'Arte Povera',
  conceptual_art: 'Konceptuális művészet',
  photorealism: 'Fotórealizmus',
  hyperrealism: 'Hiperrealizmus',
  feminist_art: 'Feminista művészet',
  pattern_and_decoration: 'Pattern & Decoration',
  supports_surfaces: 'Supports/Surfaces (Fr.)',
  neo_expressionism: 'Neo-expresszionizmus',
  transavanguardia: 'Transzavantgárd',
  neo_geo: 'Neo-Geo',
  cobra: 'Cobra',
  fluxus: 'Fluxus',
  st_ives_school: 'St Ives-i iskola (Anglia)',
  school_of_paris: 'Párizsi iskola (École de Paris)',
  transcendental_painting_group: 'Transzcendentális Festészet Csoport',
  group_of_seven: 'Group of Seven (Kanada)',
  concrete_art: 'Konkrét művészet',
  brazilian_concretism: 'Brazil konkrét művészet',
  neo_concretism: 'Neo-konkrét (Brazília)',
  argentine_madi: 'Argentín MADI',
  gutai: 'Gutai (Japán)',
  mono_ha: 'Mono-ha (Japán)',
  dansaekhwa: 'Dansaekhwa (Korea)',
  superflat: 'Superflat (Japán)',
  yba: 'YBA - Young British Artists',
  lowbrow_pop_surrealism: 'Lowbrow / Pop szürrealizmus',
  graffiti_street_art: 'Street art / graffiti',
  new_image_painting: 'New Image Painting',
  bad_painting: 'Bad Painting',
  sots_art: 'Szoc-Art (szovjet pop art)',
  new_leipzig_school: 'Új lipcsei iskola',
} as const;
