export const styleLabelsHu: Readonly<Record<string, string>> = {
  prehistoric: 'Őskori',
  ancient_egyptian: 'Ókori egyiptomi',
  ancient_greek_classical: 'Ókori görög (klasszikus)',
  hellenistic: 'Hellénisztikus',
  ancient_roman: 'Ókori római',
  late_antique: 'Késő antik',
  byzantine: 'Bizánci',
  insular: 'Insuláris (kelta-angolszász)',
  islamic: 'Iszlám (miniatúrafestészet stb.)',
  romanesque: 'Romanika',
  gothic: 'Gótika',
  proto_renaissance: 'Proto-reneszánsz (Trecento)',
  early_renaissance: 'Korai reneszánsz (Quattrocento)',
  high_renaissance: 'Magas reneszánsz',
  venetian_renaissance: 'Velencei reneszánsz',
  northern_renaissance: 'Északi reneszánsz',
  mannerism: 'Manierizmus',
  baroque: 'Barokk',
  caravaggism_tenebrism: 'Caravaggizmus / tenebrizmus',
  dutch_golden_age: 'Holland aranykor',
  rococo: 'Rokokó',
  neoclassicism: 'Neoklasszicizmus',
  romanticism: 'Romantika',
  academic_art: 'Akadémikus művészet',
  realism: 'Realizmus',
  barbizon: 'Barbizon-iskola',
  pre_raphaelite: 'Preraffaeliták',
  impressionism: 'Impresszionizmus',
  post_impressionism: 'Posztimpresszionizmus',
  pointillism_divisionism: 'Pointillizmus / Divisionizmus',
  symbolism: 'Szimbolizmus',
  art_nouveau: 'Szecesszió (Art Nouveau)',
  nabis: 'Nabis',
  fauvism: 'Fauvizmus',
  expressionism: 'Expresszionizmus',
  cubism: 'Kubizmus',
  futurism: 'Futurizmus',
  orphism: 'Orfizmus',
  metaphysical_painting: 'Metafizikus festészet',
  dada: 'Dada',
  surrealism: 'Szürrealizmus',
  suprematism: 'Szuprematizmus',
  constructivism: 'Konstruktivizmus',
  de_stijl: 'De Stijl / Neoplaszticizmus',
  bauhaus: 'Bauhaus (festői irányok)',
  precisionism: 'Precisionizmus (USA)',
  regionalism: 'Regionalizmus (USA)',
  social_realism: 'Szociális realizmus',
  abstract_art: 'Absztrakt művészet',
  abstract_expressionism: 'Absztrakt expresszionizmus',
  color_field: 'Színmező-festészet',
  art_informel_tachisme: 'Art Informel / Tachsizmus',
  lyrical_abstraction: 'Lírai absztrakció',
  hard_edge: 'Hard-edge',
  minimalism: 'Minimalizmus',
  op_art: 'Op-Art',
  pop_art: 'Pop-Art',
  post_painterly_abstraction: 'Poszt-painterly absztrakció',
  photorealism: 'Fotórealizmus',
  hyperrealism: 'Hiperrealizmus',
  neo_expressionism: 'Neo-expresszionizmus',
  transavanguardia: 'Transzavantgárd (olasz)',
  pattern_and_decoration: 'Pattern & Decoration',
  graffiti_street_art: 'Street art / graffiti',
  pop_surrealism_lowbrow: 'Pop szürrealizmus / Lowbrow',
  contemporary_figurative: 'Kortárs figurális',
  contemporary_abstract: 'Kortárs absztrakt',
  chinese_shan_shui: 'Kínai shan shui (táj)',
  chinese_gongbi: 'Kínai gongbi (finom vonalas)',
  japanese_ukiyoe: 'Japán ukiyo-e',
  nihonga: 'Nihonga',
  korean_dansakhwa: 'Koreai Dansaekhwa (monokróm)',
  mughal_miniature: 'Mogul miniatúra',
  rajput_miniature: 'Rádzsput miniatúra',
  persian_miniature: 'Perzsa miniatúra',
  ethiopian_church: 'Etióp egyházi festészet',
  russian_icon: 'Orosz ikonfestészet',
  mexican_muralism: 'Mexikói falképfestészet (muralizmus)',
  brazilian_concrete: 'Brazil konkrét művészet',
  neo_concrete: 'Neo-konkrét (Brazília)',
  argentine_madi: 'Argentín MADI',
  co_br_a: 'COBRA',
  gutai: 'Gutai',
  art_brut: 'Art Brut',
  naive_art: 'Naiv művészet',
  oriented_orientalism: 'Orientalizmus',
  other: 'Egyéb / besorolhatatlan',
} as const;
