/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppSchemasIndexRouteImport } from './routes/_app/schemas/index'
import { Route as AppQuizIndexRouteImport } from './routes/_app/quiz/index'
import { Route as AppTopicIdIndexRouteImport } from './routes/_app/$topicId/index'
import { Route as AppSchemasNewRouteImport } from './routes/_app/schemas/new'
import { Route as AppTopicIdSchemaRouteImport } from './routes/_app/$topicId/schema'
import { Route as AppTopicIdQuizConfigRouteImport } from './routes/_app/$topicId/quiz-config'
import { Route as AppTopicIdQuizRouteImport } from './routes/_app/$topicId/quiz'
import { Route as AppTopicIdItemsIndexRouteImport } from './routes/_app/$topicId/items/index'
import { Route as AppSchemasTopicIdDuplicateRouteImport } from './routes/_app/schemas/$topicId/duplicate'
import { Route as AppTopicIdItemsSuccessRouteImport } from './routes/_app/$topicId/items/success'
import { Route as AppTopicIdItemsNewRouteImport } from './routes/_app/$topicId/items/new'
import { Route as AppTopicIdItemsItemIdEditRouteImport } from './routes/_app/$topicId/items/$itemId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemasIndexRoute = AppSchemasIndexRouteImport.update({
  id: '/schemas/',
  path: '/schemas/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizIndexRoute = AppQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdIndexRoute = AppTopicIdIndexRouteImport.update({
  id: '/$topicId/',
  path: '/$topicId/',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemasNewRoute = AppSchemasNewRouteImport.update({
  id: '/schemas/new',
  path: '/schemas/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdSchemaRoute = AppTopicIdSchemaRouteImport.update({
  id: '/$topicId/schema',
  path: '/$topicId/schema',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdQuizConfigRoute = AppTopicIdQuizConfigRouteImport.update({
  id: '/$topicId/quiz-config',
  path: '/$topicId/quiz-config',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdQuizRoute = AppTopicIdQuizRouteImport.update({
  id: '/$topicId/quiz',
  path: '/$topicId/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdItemsIndexRoute = AppTopicIdItemsIndexRouteImport.update({
  id: '/$topicId/items/',
  path: '/$topicId/items/',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemasTopicIdDuplicateRoute =
  AppSchemasTopicIdDuplicateRouteImport.update({
    id: '/schemas/$topicId/duplicate',
    path: '/schemas/$topicId/duplicate',
    getParentRoute: () => AppRoute,
  } as any)
const AppTopicIdItemsSuccessRoute = AppTopicIdItemsSuccessRouteImport.update({
  id: '/$topicId/items/success',
  path: '/$topicId/items/success',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdItemsNewRoute = AppTopicIdItemsNewRouteImport.update({
  id: '/$topicId/items/new',
  path: '/$topicId/items/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdItemsItemIdEditRoute =
  AppTopicIdItemsItemIdEditRouteImport.update({
    id: '/$topicId/items/$itemId/edit',
    path: '/$topicId/items/$itemId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/$topicId/quiz': typeof AppTopicIdQuizRoute
  '/$topicId/quiz-config': typeof AppTopicIdQuizConfigRoute
  '/$topicId/schema': typeof AppTopicIdSchemaRoute
  '/schemas/new': typeof AppSchemasNewRoute
  '/$topicId/': typeof AppTopicIdIndexRoute
  '/quiz/': typeof AppQuizIndexRoute
  '/schemas/': typeof AppSchemasIndexRoute
  '/$topicId/items/new': typeof AppTopicIdItemsNewRoute
  '/$topicId/items/success': typeof AppTopicIdItemsSuccessRoute
  '/schemas/$topicId/duplicate': typeof AppSchemasTopicIdDuplicateRoute
  '/$topicId/items/': typeof AppTopicIdItemsIndexRoute
  '/$topicId/items/$itemId/edit': typeof AppTopicIdItemsItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/$topicId/quiz': typeof AppTopicIdQuizRoute
  '/$topicId/quiz-config': typeof AppTopicIdQuizConfigRoute
  '/$topicId/schema': typeof AppTopicIdSchemaRoute
  '/schemas/new': typeof AppSchemasNewRoute
  '/$topicId': typeof AppTopicIdIndexRoute
  '/quiz': typeof AppQuizIndexRoute
  '/schemas': typeof AppSchemasIndexRoute
  '/$topicId/items/new': typeof AppTopicIdItemsNewRoute
  '/$topicId/items/success': typeof AppTopicIdItemsSuccessRoute
  '/schemas/$topicId/duplicate': typeof AppSchemasTopicIdDuplicateRoute
  '/$topicId/items': typeof AppTopicIdItemsIndexRoute
  '/$topicId/items/$itemId/edit': typeof AppTopicIdItemsItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/$topicId/quiz': typeof AppTopicIdQuizRoute
  '/_app/$topicId/quiz-config': typeof AppTopicIdQuizConfigRoute
  '/_app/$topicId/schema': typeof AppTopicIdSchemaRoute
  '/_app/schemas/new': typeof AppSchemasNewRoute
  '/_app/$topicId/': typeof AppTopicIdIndexRoute
  '/_app/quiz/': typeof AppQuizIndexRoute
  '/_app/schemas/': typeof AppSchemasIndexRoute
  '/_app/$topicId/items/new': typeof AppTopicIdItemsNewRoute
  '/_app/$topicId/items/success': typeof AppTopicIdItemsSuccessRoute
  '/_app/schemas/$topicId/duplicate': typeof AppSchemasTopicIdDuplicateRoute
  '/_app/$topicId/items/': typeof AppTopicIdItemsIndexRoute
  '/_app/$topicId/items/$itemId/edit': typeof AppTopicIdItemsItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/$topicId/quiz'
    | '/$topicId/quiz-config'
    | '/$topicId/schema'
    | '/schemas/new'
    | '/$topicId/'
    | '/quiz/'
    | '/schemas/'
    | '/$topicId/items/new'
    | '/$topicId/items/success'
    | '/schemas/$topicId/duplicate'
    | '/$topicId/items/'
    | '/$topicId/items/$itemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/$topicId/quiz'
    | '/$topicId/quiz-config'
    | '/$topicId/schema'
    | '/schemas/new'
    | '/$topicId'
    | '/quiz'
    | '/schemas'
    | '/$topicId/items/new'
    | '/$topicId/items/success'
    | '/schemas/$topicId/duplicate'
    | '/$topicId/items'
    | '/$topicId/items/$itemId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/home'
    | '/_app/$topicId/quiz'
    | '/_app/$topicId/quiz-config'
    | '/_app/$topicId/schema'
    | '/_app/schemas/new'
    | '/_app/$topicId/'
    | '/_app/quiz/'
    | '/_app/schemas/'
    | '/_app/$topicId/items/new'
    | '/_app/$topicId/items/success'
    | '/_app/schemas/$topicId/duplicate'
    | '/_app/$topicId/items/'
    | '/_app/$topicId/items/$itemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemas/': {
      id: '/_app/schemas/'
      path: '/schemas'
      fullPath: '/schemas/'
      preLoaderRoute: typeof AppSchemasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/': {
      id: '/_app/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof AppQuizIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/': {
      id: '/_app/$topicId/'
      path: '/$topicId'
      fullPath: '/$topicId/'
      preLoaderRoute: typeof AppTopicIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemas/new': {
      id: '/_app/schemas/new'
      path: '/schemas/new'
      fullPath: '/schemas/new'
      preLoaderRoute: typeof AppSchemasNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/schema': {
      id: '/_app/$topicId/schema'
      path: '/$topicId/schema'
      fullPath: '/$topicId/schema'
      preLoaderRoute: typeof AppTopicIdSchemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/quiz-config': {
      id: '/_app/$topicId/quiz-config'
      path: '/$topicId/quiz-config'
      fullPath: '/$topicId/quiz-config'
      preLoaderRoute: typeof AppTopicIdQuizConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/quiz': {
      id: '/_app/$topicId/quiz'
      path: '/$topicId/quiz'
      fullPath: '/$topicId/quiz'
      preLoaderRoute: typeof AppTopicIdQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/items/': {
      id: '/_app/$topicId/items/'
      path: '/$topicId/items'
      fullPath: '/$topicId/items/'
      preLoaderRoute: typeof AppTopicIdItemsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemas/$topicId/duplicate': {
      id: '/_app/schemas/$topicId/duplicate'
      path: '/schemas/$topicId/duplicate'
      fullPath: '/schemas/$topicId/duplicate'
      preLoaderRoute: typeof AppSchemasTopicIdDuplicateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/items/success': {
      id: '/_app/$topicId/items/success'
      path: '/$topicId/items/success'
      fullPath: '/$topicId/items/success'
      preLoaderRoute: typeof AppTopicIdItemsSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/items/new': {
      id: '/_app/$topicId/items/new'
      path: '/$topicId/items/new'
      fullPath: '/$topicId/items/new'
      preLoaderRoute: typeof AppTopicIdItemsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/items/$itemId/edit': {
      id: '/_app/$topicId/items/$itemId/edit'
      path: '/$topicId/items/$itemId/edit'
      fullPath: '/$topicId/items/$itemId/edit'
      preLoaderRoute: typeof AppTopicIdItemsItemIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppTopicIdQuizRoute: typeof AppTopicIdQuizRoute
  AppTopicIdQuizConfigRoute: typeof AppTopicIdQuizConfigRoute
  AppTopicIdSchemaRoute: typeof AppTopicIdSchemaRoute
  AppSchemasNewRoute: typeof AppSchemasNewRoute
  AppTopicIdIndexRoute: typeof AppTopicIdIndexRoute
  AppQuizIndexRoute: typeof AppQuizIndexRoute
  AppSchemasIndexRoute: typeof AppSchemasIndexRoute
  AppTopicIdItemsNewRoute: typeof AppTopicIdItemsNewRoute
  AppTopicIdItemsSuccessRoute: typeof AppTopicIdItemsSuccessRoute
  AppSchemasTopicIdDuplicateRoute: typeof AppSchemasTopicIdDuplicateRoute
  AppTopicIdItemsIndexRoute: typeof AppTopicIdItemsIndexRoute
  AppTopicIdItemsItemIdEditRoute: typeof AppTopicIdItemsItemIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppTopicIdQuizRoute: AppTopicIdQuizRoute,
  AppTopicIdQuizConfigRoute: AppTopicIdQuizConfigRoute,
  AppTopicIdSchemaRoute: AppTopicIdSchemaRoute,
  AppSchemasNewRoute: AppSchemasNewRoute,
  AppTopicIdIndexRoute: AppTopicIdIndexRoute,
  AppQuizIndexRoute: AppQuizIndexRoute,
  AppSchemasIndexRoute: AppSchemasIndexRoute,
  AppTopicIdItemsNewRoute: AppTopicIdItemsNewRoute,
  AppTopicIdItemsSuccessRoute: AppTopicIdItemsSuccessRoute,
  AppSchemasTopicIdDuplicateRoute: AppSchemasTopicIdDuplicateRoute,
  AppTopicIdItemsIndexRoute: AppTopicIdItemsIndexRoute,
  AppTopicIdItemsItemIdEditRoute: AppTopicIdItemsItemIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
