/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppQuizIndexRouteImport } from './routes/_app/quiz/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTopicIdIndexRouteImport } from './routes/_app/$topicId/index'
import { Route as AppAdminTopicIdIndexRouteImport } from './routes/_app/admin/$topicId/index'
import { Route as AppAdminTopicIdSuccessRouteImport } from './routes/_app/admin/$topicId/success'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizIndexRoute = AppQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicIdIndexRoute = AppTopicIdIndexRouteImport.update({
  id: '/$topicId/',
  path: '/$topicId/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTopicIdIndexRoute = AppAdminTopicIdIndexRouteImport.update({
  id: '/admin/$topicId/',
  path: '/admin/$topicId/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTopicIdSuccessRoute = AppAdminTopicIdSuccessRouteImport.update({
  id: '/admin/$topicId/success',
  path: '/admin/$topicId/success',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/$topicId/': typeof AppTopicIdIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/quiz/': typeof AppQuizIndexRoute
  '/admin/$topicId/success': typeof AppAdminTopicIdSuccessRoute
  '/admin/$topicId/': typeof AppAdminTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/$topicId': typeof AppTopicIdIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/quiz': typeof AppQuizIndexRoute
  '/admin/$topicId/success': typeof AppAdminTopicIdSuccessRoute
  '/admin/$topicId': typeof AppAdminTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/$topicId/': typeof AppTopicIdIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/quiz/': typeof AppQuizIndexRoute
  '/_app/admin/$topicId/success': typeof AppAdminTopicIdSuccessRoute
  '/_app/admin/$topicId/': typeof AppAdminTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/$topicId/'
    | '/admin/'
    | '/quiz/'
    | '/admin/$topicId/success'
    | '/admin/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/$topicId'
    | '/admin'
    | '/quiz'
    | '/admin/$topicId/success'
    | '/admin/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/home'
    | '/_app/$topicId/'
    | '/_app/admin/'
    | '/_app/quiz/'
    | '/_app/admin/$topicId/success'
    | '/_app/admin/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/': {
      id: '/_app/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof AppQuizIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$topicId/': {
      id: '/_app/$topicId/'
      path: '/$topicId'
      fullPath: '/$topicId/'
      preLoaderRoute: typeof AppTopicIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/$topicId/': {
      id: '/_app/admin/$topicId/'
      path: '/admin/$topicId'
      fullPath: '/admin/$topicId/'
      preLoaderRoute: typeof AppAdminTopicIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/$topicId/success': {
      id: '/_app/admin/$topicId/success'
      path: '/admin/$topicId/success'
      fullPath: '/admin/$topicId/success'
      preLoaderRoute: typeof AppAdminTopicIdSuccessRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppTopicIdIndexRoute: typeof AppTopicIdIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppQuizIndexRoute: typeof AppQuizIndexRoute
  AppAdminTopicIdSuccessRoute: typeof AppAdminTopicIdSuccessRoute
  AppAdminTopicIdIndexRoute: typeof AppAdminTopicIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppTopicIdIndexRoute: AppTopicIdIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppQuizIndexRoute: AppQuizIndexRoute,
  AppAdminTopicIdSuccessRoute: AppAdminTopicIdSuccessRoute,
  AppAdminTopicIdIndexRoute: AppAdminTopicIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
